<?php 
die('dev');
	$token = Mage::app()->getRequest()->getParam('token'); 
	if($token != ''):	
?>
	<script src="http://dev.zooz.co:8090/mobile/js/zooz-ext-web-ajax.js"></script>
	<script type="text/javascript">
		<?php if(Mage::getModel('zoozpayment/standard')->getIsSandBox()): ?>
		var	sandbox = true;
		<?php else: ?>
		var sandbox = false;
		<?php endif; ?>	
		
		jQuery(document).ready(function(){
			zoozStartCheckout({
				token : "<?php echo $token; ?>",
				uniqueId : "<?php echo Mage::getModel('zoozpayment/standard')->getAppUniqueId(); ?>",
				isSandbox : sandbox,
				returnUrl : "<?php echo $this->getUrl('zoozpayment/standard/successexpress');?>",
				cancelUrl : "<?php echo $this->getUrl('zoozpayment/standard/cancel');?>"
				
			});
		});
	</script>
<?php else: ?>
	<p>No content</p>
<?php endif; ?>

        