<a id="zooz-payment-link" style="background-color: #679100; padding: 10px; color: white; font-size: small;"  href="<?php echo $this->getUrl('zoozpayment/standard/ajaxstart');?>" onclick='return localDoZooz(this);' >Checkout
</a>
<img id="zooz-payment-loading" class='zooz-payment-loading' style="display: none; margin-left: 10px;z-index:1000" src="<?php echo $this->getSkinUrl('zooz/images/loading.gif');?>" alt="loading" title="loading" />
<style>
	.cart .title-buttons .checkout-types li { float: none; }
</style>
<script  type="text/javascript">
function localDoZooz(ref){
        var isSandbox = <?php echo Mage::getModel('zoozpayment/standard')->getIsSandBox(); ?>;
        var formObject = jQuery('#product_addtocart_form');
        var url = jQuery(ref).attr('href');
        var uniqueId = "<?php echo Mage::getModel('zoozpayment/standard')->getAppUniqueId(); ?>";
        var returnUrl = "<?php echo $this->getUrl('zoozpayment/standard/successexpress');?>";
        var cancelUrl = "<?php echo $this->getUrl('zoozpayment/standard/cancel');?>"; 
        startZooz(isSandbox, formObject, url, uniqueId, returnUrl, cancelUrl);
        
        return false;
}
</script>
