
<br/>
<br/>
<a id="zooz-payment-link" style="float: right; background-color: #679100; padding: 10px; color: white; font-size: small;"  href="<?php echo $this->getUrl('zoozpayment/cart/add'); ?>" onclick="return localDoZooz(this);">
Quick Checkout
</a>
<img id="zooz-payment-loading" class="zooz-payment-loading" style="display: none; margin-left: 10px;" src="<?php echo $this->getSkinUrl('zooz/images/loading.gif'); ?>" alt="loading" title="loading" />
<script type="text/javascript">


function localDoZooz(ref){
	var isSandbox = <?php echo Mage::getModel('zoozpayment/standard')->getIsSandBox(); ?>;
	var formObject = jQuery('#product_addtocart_form');
	var url = jQuery(ref).attr('href');
	var uniqueId = "<?php echo Mage::getModel('zoozpayment/standard')->getAppUniqueId(); ?>";
	var returnUrl = "<?php echo $this->getUrl('zoozpayment/standard/successexpress');?>";
	var cancelUrl = "<?php echo $this->getUrl('zoozpayment/standard/cancel');?>"; 
	startZooz(isSandbox, formObject, url, uniqueId, returnUrl, cancelUrl);
	
	return false;
}
</script>
